# Generated by Django 2.1.7 on 2019-09-12 15:49

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0002_auto_20190912_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='contact_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
