# Generated by Django 2.1.5 on 2019-01-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0002_auto_20190116_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistimage',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
