# Generated by Django 2.1.5 on 2019-01-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0003_auto_20190116_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_pic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
