# Generated by Django 2.1.7 on 2019-10-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0004_auto_20190920_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='contact_last_name',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='contact_phone',
        ),
    ]
