# Generated by Django 2.1.5 on 2019-01-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0004_artistprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
