# Generated by Django 2.1.5 on 2019-01-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0005_auto_20190118_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_pic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
