# Generated by Django 2.1.7 on 2019-10-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0005_auto_20191012_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
