# Generated by Django 2.1.5 on 2019-01-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0006_auto_20190118_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='bandcamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
