# Generated by Django 2.1.5 on 2019-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0007_auto_20190118_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
