# Generated by Django 2.1.5 on 2019-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_profile', '0008_auto_20190118_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
