# Generated by Django 2.1.5 on 2019-01-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist_profile', '0005_auto_20190118_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('performers', models.CharField(max_length=200)),
                ('guarantee', models.IntegerField()),
                ('door_split', models.BooleanField()),
                ('hotel_needed', models.BooleanField()),
                ('venu_size', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('region', models.CharField(max_length=10)),
                ('tour_pic', models.IntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_profile.ArtistProfile')),
            ],
        ),
    ]
