# Generated by Django 2.1.5 on 2019-01-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20190118_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='venu_size',
            new_name='venue_size',
        ),
    ]
