# Generated by Django 2.1.5 on 2019-01-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20190119_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='door_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotel_needed',
            field=models.BooleanField(default=False),
        ),
    ]
