# Generated by Django 2.1.5 on 2019-01-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_auto_20190122_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
