# Generated by Django 2.1.5 on 2019-01-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20190122_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
