# Generated by Django 2.1.5 on 2019-01-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city_list',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
