# Generated by Django 2.1.5 on 2019-01-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tour_city_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city_list',
            field=models.TextField(),
        ),
    ]
