# Generated by Django 2.1.5 on 2019-01-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20190122_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='region',
            field=models.CharField(max_length=20),
        ),
    ]
