# Generated by Django 2.1.5 on 2019-03-27 21:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20190123_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=True, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
